version: "3"

networks:
  internal-api-test:
    external: true

volumes:
  test_data:

services:
  api_test:
    container_name: api_test
    # command: "go run main.go"
    build: ./api_test
    tty: true
    volumes:
      - ./api_test:/go/api_test
    depends_on:
      - mysql_test
    ports:
      - 8080:8080
    networks:
      - internal-api-test

  mysql_test:
    platform: linux/amd64
    build: ./api_test/db
    container_name: test_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - test_data:/var/lib/mysql
    networks:
      - internal-api-test
